Repository digitomize/digitomize, pull requests merged in 2023-10, with the labels that each got.

#109 skeleton
  client/src/components/Filter.jsx
  client/src/user/dashboard/UserDashboard.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#106 scrollToTop
  client/src/components/Filter.jsx
  client/src/components/ScrollToTop.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#113 Version2
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/components/Contests.jsx
  client/src/components/CustomSlider.jsx
  client/src/components/Filter.jsx
Labels: hacktoberfest

#132 fix(filter): define shrink state
  client/src/components/Filter.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#107 Update README.md
  README.md
Labels: hacktoberfest

#142 added spinner in discord redirect
  client/src/App.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#130 fix: hover on cards
  client/src/components/css/Card.css
Labels: hacktoberfest, hacktoberfest-accepted

#141 Hacktober-fest-route
  client/src/assets/hacktoberImg.jpeg
  client/src/components/Hacktoberfest.jsx
  client/src/components/css/Hacktoberfest.css
  client/src/main.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#147 Added to individual page
  client/src/components/IndividualCard.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#148 main->develop
  README.md
  client/src/App.css
  client/src/App.jsx
  client/src/assets/hacktoberImg.jpeg
  client/src/components/Button.jsx
  client/src/components/Contests.jsx
  client/src/components/Filter.jsx
  client/src/components/Hacktoberfest.jsx
  client/src/components/HeroSection.jsx
  client/src/components/IndividualCard.jsx
  client/src/components/Navbar.jsx
  client/src/components/SignoutButton.jsx
  client/src/components/css/Card.css
  client/src/components/css/Filter.css
  client/src/components/css/Hacktoberfest.css
  client/src/components/css/IndividualCard.css
  client/src/components/css/Navbar.css
  client/src/main.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#146 removed extra line spaces and unused import
  client/api.js
  client/src/components/Card.jsx
  client/src/components/IndividualCard.jsx
  client/src/components/Layout.jsx
  client/src/components/Login.jsx
  client/src/components/Signup.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#139 Fix UI issues in login and signup pages
  client/src/components/Login.jsx
  client/src/components/Signup.jsx
  client/src/components/css/Login.css
  client/src/user/components/SignoutButton.jsx
  client/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#177 Add: atCoder contest
  backend/contest/controllers/DataSyncController.js
  backend/contest/controllers/platforms/atcoderController.js
  backend/package-lock.json
  backend/package.json
  client/src/assets/atcoder.svg
  client/src/components/AllAssets.jsx
  client/src/components/Card.jsx
  client/src/components/Filter.jsx
  client/src/components/HomePage2.jsx
  client/src/components/IndividualCard.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#190 refactor: navbar code
  client/src/components/Navbar.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#194 Updated ES5 code to ES6.
  backend/contest/controllers/DataSyncController.js
  backend/contest/controllers/contestController.js
  backend/contest/controllers/platforms/atcoderController.js
  backend/contest/controllers/platforms/codechefController.js
  backend/contest/controllers/platforms/codeforcesController.js
  backend/contest/controllers/platforms/codingninjas_studioController.js
  backend/contest/controllers/platforms/gfgController.js
  backend/contest/controllers/platforms/leetcodeController.js
  backend/contest/models/Contest.js
  backend/contest/routes/contestRoutes.js
  backend/fetchContests.js
  backend/index.js
  backend/package.json
  backend/users/controllers/authController.js
  backend/users/controllers/platforms/codechefUpdater.js
  backend/users/controllers/platforms/codeforcesUpdater.js
  backend/users/controllers/platforms/leetcodeUpdater.js
  backend/users/controllers/userDashboardController.js
  backend/users/controllers/userProfileController.js
  backend/users/controllers/userUpdateController.js
  backend/users/middlewares/authMiddleware.js
  backend/users/models/User.js
  backend/users/routes/userRoutes.js
  backend/users/services/getUser.js
  backend/users/services/setUser.js
  backend/users/services/updateUser.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#197 Leaderboard for users
  backend/users/controllers/leaderboardController.js
  backend/users/routes/userRoutes.js
  client/api.js
  client/src/App.jsx
  client/src/components/NewNavbar.jsx
  client/src/user/leaderboard/Leaderboard.jsx
Labels: enhancement, hacktoberfest

#208 Use postinstall script
  README.md
  package-lock.json
  package.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#209 use postinstall script (version2 branch)
  README.md
  package-lock.json
  package.json
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#201 added username and name on email password signup
  backend/users/controllers/authController.js
  backend/users/services/setUser.js
  client/src/components/Signup.jsx
  client/src/context/UserAuthContext.jsx
  client/src/user/dashboard/UserDashboard.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#211 Add a Hover/Transition Effect Over 'go to contest button'!!
  client/src/components/HeroSection.jsx
  client/src/components/css/Card.css
  client/src/components/css/HeroSection.css
Labels: enhancement, good first issue, hacktoberfest

#219 EnhancedErrorHandling#215
  backend/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#187 share-modal-ui
  backend/package.json
  client/index.html
  client/src/components/Card.jsx
  client/src/components/Contests.jsx
  client/src/components/CopyToClipboard.jsx
  client/src/components/css/socials.css
  client/src/components/share_model.jsx
Labels: enhancement, hacktoberfest
